development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: thornbare_development

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: thornbare_production
